const cadJsonBDH=`[
    {
      "id_BNE": "a4564505",
      "autor_personas": "Laborda y Galve, Agustín -imp.  // ",
      "título": "Gozos al Arcangel San Miguel, venerado en el beaterio y eremitorio de la villa de Liria ",
      "editorial": "imprenta de Laborda  ",
      "lugar_publicacion": "Valencia",
      "fecha_publicacion": "entre 1830 y 1864?",
      "descripcion_fisica": "[1] h. , 31 cm. , ",
      "descripcion_notas": "Fechas de impresión deducidas de los datos de actividad de la imprenta, dirigida en esos años por Agustín Laborda  // Texto a tres columnas y con orla tipográfica  // Hoja impresa por una sola cara  // Grabado xilográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Valencia, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/92 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153646&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153646&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4564518",
      "autor_entidades": "Imprenta de Torras -Imp.  // ",
      "título": "Gozos al glorioso San Luciano y Compañeros Mrs. su fiesta á 8 de Enero ",
      "editorial": "imp. de Torras, calle S. Eusebio núm. 6  ",
      "lugar_publicacion": "S. Gervasio [Barcelona]",
      "fecha_publicacion": "1886",
      "descripcion_fisica": "[1] h. , 31 cm , ",
      "descripcion_notas": "Hoja impresa por una sola cara  // Texto a tres columnas y con orla tipográfica  // Grabados xilográficos en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Barcelona, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/96 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153650&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153650&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4564528",
      "autor_entidades": "Imprenta de Torras -Imp.  // ",
      "título": "Gozos en alabanza del inclito centurion y martir S. Longinos su fiesta el dia 15 de Marzo ",
      "editorial": "imp. de Torras, calle de S. Eusebio n. 6  ",
      "lugar_publicacion": "S. Gervasio [Barcelona]",
      "fecha_publicacion": "entre 1870 y 1900?",
      "descripcion_fisica": "[1] h. , 31 cm , ",
      "descripcion_notas": "Fechas de impresión deducidas de los datos de actividad de la imprenta  // Texto a tres columnas y con orla tipográfica  // Hoja impresa por una sola cara  // Grabado xilográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Barcelona, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/97 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153651&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153651&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4564536",
      "autor_entidades": "Imprenta Tasso -Imp.  // ",
      "título": "Gozos del glorioso San Leon IX, Papa y confesor cuya fiesta se celebra en el dia 19 de abril ",
      "editorial": "imp. Tasso  ",
      "lugar_publicacion": "[Barcelona]",
      "fecha_publicacion": "entre 1835 y 1918?",
      "descripcion_fisica": "[1] h. , 31 cm , ",
      "descripcion_notas": "Lugar y fechas de impresión deducidos de los datos de actividad de la imprenta  // Texto a tres columnas y con orla tipográfica  // Hoja impresa por una sola cara  // Grabado litográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Barcelona, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/98 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153652&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153652&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4564601",
      "autor_entidades": "Imprenta de Torras -Imp.  // ",
      "título": "Gozos al glorioso doctor de la Iglesia San Leon Papa que se celebra el dia 11 de Abril ",
      "editorial": "imp. de Torras, calle de S. Eusebio núm. 6  ",
      "lugar_publicacion": "San Gervasio [Barcelona]",
      "fecha_publicacion": "1885",
      "descripcion_fisica": "[1] h. , 31 cm , ",
      "descripcion_notas": "Texto a tres columnas y con orla tipográfica  // Hoja impresa por una sola cara  // Grabado xilográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Barcelona, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/101 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153655&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153655&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4564644",
      "autor_entidades": "Imprenta Tasso -Imp.  // ",
      "título": "Gozos del glorioso mendigo Beato Benito José Labre, confesor beatificado por el papa Pio IX (de santa memoria) en 20 de mayo de 1860 : celébrase su fiesta en el dia 16 de abril ",
      "editorial": "imp. Tasso, Arco del Teatro, 21 y 23  ",
      "lugar_publicacion": "Barcelona",
      "fecha_publicacion": "entre 1860 y 1906?",
      "descripcion_fisica": "[1] h. , 31 cm , ",
      "descripcion_notas": "Fecha de impresión deducida a partir del título  // La Imprenta de Tasso imprime entre 1835 y 1906  // Texto a tres columnas y con orla tipográfica  // Hoja impresa por una sola cara  // Grabado litográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Barcelona, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/104 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153658&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153658&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4564660",
      "autor_entidades": "Tipografía Española (Barcelona) -Imp.  // ",
      "título": "Gozos de San Leandro, arzobispo y doctor su fiesta en el dia 27 de Febrero ",
      "editorial": "Tipografía Española, Hospital, 87  ",
      "lugar_publicacion": "[Barcelona]",
      "fecha_publicacion": "entre 1875 y 1900?",
      "descripcion_fisica": "[1] h. , 31 cm , ",
      "descripcion_notas": "Lugar y fechas de impresión deducidos de los datos de actividad de la imprenta  // Hoja impresa por una sola cara  // Texto a tres columnas y con orla tipográfica  // Grabado litográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Barcelona, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/105 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153659&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153659&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4564666",
      "autor_entidades": "Herederos de la Viuda de Pla -Imp.  // ",
      "título": "Gozos al glorioso obispo S. Liborio ",
      "editorial": "imprenta de los Herederos de la V. Pla  ",
      "lugar_publicacion": "Barcelona",
      "fecha_publicacion": "entre 1845 y 1900?",
      "descripcion_fisica": "[1] h. , 31 cm , ",
      "descripcion_notas": "Fechas de impresión deducidas de los datos de actividad de la imprenta  // Por tipografía, impreso en el siglo XIX  // Hoja impresa por una sola cara  // Texto a dos columnas y con orla tipográfica  // Grabado xilográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Barcelona, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/106 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153660&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153660&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4564669",
      "autor_personas": "Sante Loy, Antonio de  // ",
      "título": "Aqui se contienen dos xacaras famosas La vna, de las quexas que le dà vn tio a su sobrino, entrambos Verdugos en Valladolid, despues de auerle açotado La otra, sobre lo que vulgarmente suena en Madrid por los chascos de la Margaritona ",
      "informacion_asociada_titulo": "compuesta por Antonio de Sante Loy ",
      "editorial": "por Andres Garcia  ",
      "lugar_publicacion": "Con licencia En Madrid",
      "fecha_publicacion": "1656",
      "descripcion_fisica": "[4] h. , 16º , ",
      "descripcion_notas": "Con reclamos, a línea tirada  // ",
      "transcripciones_interes": "EScucheme todo jaque, / todo curioso me asista, O Quieras Musa, o no quieras, / ò soples bien, ò no soples, ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/46/89 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000152831&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000152831&first=1&last=15 ** "
    },
    {
      "id_BNE": "a4564674",
      "autor_personas": "Marti, Juan -imp.  // ",
      "título": "Gozos al glorioso padre San Luis Bertran, venerado en su ermita de la villa de Buñol ",
      "editorial": "imprenta de Juan Martí (antes de Laborda), Bolsería, 24  ",
      "lugar_publicacion": "Valencia",
      "fecha_publicacion": "entre 1864 y 1867?",
      "descripcion_fisica": "[1] h. , 29 cm , ",
      "descripcion_notas": "Fecha de impresión deducida de los años de trabajo del impresor en Valencia, a partir de 1867 hasta aproximadamente 1876 sólo trabaja como librero  // Hoja impresa por una sola cara  // Texto a tres columnas y con orla tipográfica  // Grabado xilográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Valencia, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/107 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153661&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153661&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4564739",
      "autor_entidades": "Imprenta de Torras -Imp.  // ",
      "título": "Gozos del glorioso San Lamberto Labrador Martir su fiesta en 16 de Abril ",
      "editorial": "imprenta de Torras, calle de S. Eusebio núm. 6  ",
      "lugar_publicacion": "S. Gervasio [Barcelona]",
      "fecha_publicacion": "1886",
      "descripcion_fisica": "[1] h. , 31 cm , ",
      "descripcion_notas": "Texto a dos columnas y con orla tipográfica  // Hoja impresa por una sola cara  // Grabado xilográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Barcelona, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/111 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153662&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153662&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4564748",
      "autor_entidades": "Imprenta Tasso -Imp.  // ",
      "título": "Gozos de San Leonardo de Portu-Mauricio, confesor, canonizado por Pio IX en 1867 ",
      "editorial": "imp. Tasso, Arco del Teatro, 21 y 23  ",
      "lugar_publicacion": "Barcelona",
      "fecha_publicacion": "entre 1867 y 1906?",
      "descripcion_fisica": "[1] h. , 31 cm , ",
      "descripcion_notas": "Fecha de impresión deducida del título ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Barcelona, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/112 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153663&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153663&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4564760",
      "autor_entidades": "Imprenta de Torras -Imp.  // ",
      "título": "Gozos en honor del esclarecido obispo y confesor San Lope su fiesta en 25 Setiembre ",
      "editorial": "imprenta de Torras, calle de S. Eusebio núm. 6  ",
      "lugar_publicacion": "[Barcelona]",
      "fecha_publicacion": "1885",
      "descripcion_fisica": "[1] h. , 31 cm. , ",
      "descripcion_notas": "Lugar de impresión deducido de los datos de actividad de la imprenta  // Texto a tres columnas y con orla tipográfica  // Hoja impresa por una sola cara  // Grabado litográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Barcelona, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/113 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153664&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153664&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4564772",
      "autor_entidades": "Imprenta Tasso -Imp.  // ",
      "título": "Gozos del glorioso San Lino, papa y mártir cuya fiesta se celebra en 23 de setiembre ",
      "editorial": "imp. Tasso, hijo  ",
      "lugar_publicacion": "[Barcelona]",
      "fecha_publicacion": "entre 1835 y 1918?",
      "descripcion_fisica": "[1] h. , 30 cm , ",
      "descripcion_notas": "Lugar y fechas de impresión deducidos de los datos de actividad de la imprenta  // Texto a tres columnas y con orla tipográfica  // Hoja impresa por una sola cara  // Grabado litográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Barcelona, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/114 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153665&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153665&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4564789",
      "autor_entidades": "Viuda de Torras -Imp.  // ",
      "título": "Gozos de S. Luis Rey de Francia, patron de la venerable orden tercera de penitencia de N. S. P. S. Francisco de Asis ",
      "editorial": "imprenta de la viuda Torras  ",
      "lugar_publicacion": "Barcelona",
      "fecha_publicacion": "entre 1848 y 1900?",
      "descripcion_fisica": "[1] h. , 31 cm , ",
      "descripcion_notas": "Fechas de impresión deducidas de los datos de actividad de la imprenta  // Texto a tres columnas y con orla tipográfica  // Hoja impresa por una sola cara  // Grabado en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Barcelona, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/115 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153666&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153666&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4564800",
      "autor_entidades": "Imprenta y Librería de la Inmaculada Concepción -Imp.  // ",
      "título": "Gozos de San Lorenzo de Brindis ",
      "editorial": "imp. y librería de la Inmaculada Concepcion, Buensuceso 13, y Pasaje de la Merced 10  ",
      "lugar_publicacion": "Barcelona",
      "fecha_publicacion": "entre 1880 y 1900?",
      "descripcion_fisica": "[1] h. , 31 cm , ",
      "descripcion_notas": "Precede al título: Biblioteca Seráfica  // Fechas de impresión deducidas de la actividad conocida de la librería  // Texto a tres columnas y con orla tipográfica  // Hoja impresa por una sola cara  // Grabado litográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Barcelona, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/116 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153667&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153667&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4564820",
      "autor_entidades": "Tipografía Española (Barcelona) -Imp.  // ",
      "título": "Gozos del Beato Juan de Parma, confesor de la órden de San Francisco cuya fiesta se celebra en el dia 20 de marzo ",
      "editorial": "Tipografía Española, Hospital, 87  ",
      "lugar_publicacion": "Barcelona",
      "fecha_publicacion": "entre 1875 y 1900?",
      "descripcion_fisica": "[1] h. , 31 cm , ",
      "descripcion_notas": "Fechas de impresión deducidas de los datos de actividad de la imprenta  // Texto a tres columnas y con orla tipográfica  // Hoja impresa por una sola cara  // Grabado litográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Barcelona, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/120 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153671&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153671&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4564830",
      "autor_entidades": "Herederos de la Viuda de Pla -Imp.  // ",
      "título": "Gozos en elogio del beato doctor Joseph Oriol, dignísimo monacillo que fué de la Parroquial Iglesia de Santa María del Mar, de la presente ciudad ",
      "edicion": "Nueva edicion",
      "editorial": "imp. de los H. de la V. Pla, Princesa, 8  ",
      "lugar_publicacion": "Barcelona",
      "fecha_publicacion": "1893",
      "descripcion_fisica": "[4] p. , 31 cm. , ",
      "descripcion_notas": "Texto del gozo a tres columnas y de las Notas a dos  // Texto con orla tipográfica  // Grabado y escudos xilográficos en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Barcelona, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/121 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153672&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153672&first=1&last=4 ** "
    },
    {
      "id_BNE": "a4564849",
      "autor_entidades": "Herederos de la Viuda de Pla -Imp.  // ",
      "título": "Gozos en alabanza del glorioso precursor San Juan Bautista ",
      "editorial": "imprenta de los Herederos de la V. Pla, calle de la Princesa  ",
      "lugar_publicacion": "Barcelona",
      "fecha_publicacion": "entre 1854 y 1900?",
      "descripcion_fisica": "[1] h. , 32 cm , ",
      "descripcion_notas": "Fechas de impresión deducidas de los datos de actividad de la imprenta  // Por tipografía, impreso en el siglo XIX  // Hoja impresa por una sola cara  // Texto a tres columnas y con orla tipográfica  // Grabado xilográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Barcelona, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/123 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153674&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153674&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4564882",
      "autor_entidades": "Herederos de la Viuda de Pla -Imp.  // ",
      "título": "Súplicas al Patriarca San José para obtener una buena muerte ",
      "editorial": "imp. de los H. de la V. Pla, Princesa, 8  ",
      "lugar_publicacion": "Barcelona",
      "fecha_publicacion": "1887",
      "descripcion_fisica": "[1] h. , 31 cm. , ",
      "descripcion_notas": "Texto a tres columnas y con orla tipográfica  // Hoja impresa por una sola cara  // Grabado litográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Barcelona, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/127 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153678&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153678&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4564892",
      "autor_personas": "Isuar, Salvador -imp.  // ",
      "título": "Endechas a manera de gozos al patriarca San José para conseguir una buena muerte con su patrocinio ",
      "editorial": "imp. de S. Isuar  ",
      "lugar_publicacion": "Tortosa",
      "fecha_publicacion": "1863",
      "descripcion_fisica": "[1] h. , 31 cm , ",
      "descripcion_notas": "Hoja impresa por una sola cara  // Texto a dos columnas y con orla tipográfica  // Grabado xilográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Tortosa, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/128 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153679&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153679&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4564902",
      "autor_personas": "Martí Casanova, José , fl. 1856-1895 -imp.  // ",
      "título": "Gozos a San Juan Bautista, titular de la iglesia del barrio del Pas del Cenia en la parroquia y termino municipal de Ulldecona ",
      "editorial": "impr. de José Martí, c. Zaragoza, 15  ",
      "lugar_publicacion": "Valencia",
      "fecha_publicacion": "entre 1871 y 1895?",
      "descripcion_fisica": "[1] h. , 31 cm , ",
      "descripcion_notas": "Fechas de impresión deducidas de los años de trabajo del impresor en Valencia  // Texto a tres columnas y con orla tipográfica  // Hoja impresa por una sola cara  // Grabado xilográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Valencia, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/133 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153682&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153682&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4564908",
      "título": "Gozos a San Indalecio, obispo y mártir se celebra su fiesta el dia 15 de Mayo ",
      "editorial": "s.n.]  ",
      "lugar_publicacion": "[S.l.",
      "fecha_publicacion": "entre 1850 y 1900?",
      "descripcion_fisica": "[1] h. , 32 cm , ",
      "descripcion_notas": "Por tipografía, impreso en la segunda mitad del siglo XIX  // Texto a tres columnas y con orla tipográfica  // Hoja impresa por una sola cara  // Grabado litográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/136 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153685&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153685&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4564917",
      "autor_personas": "Laborda y Galve, Agustín -imp.  // ",
      "título": "Gozos al Niño Jesus recien nacido ",
      "editorial": "Imprenta Laborda  ",
      "lugar_publicacion": "Valencia",
      "fecha_publicacion": "entre 1830 y 1864?",
      "descripcion_fisica": "[1] h. , 31 cm. , ",
      "descripcion_notas": "Existen al menos dos ediciones  // Fecha de impresión deducida de los años de trabajo del impresor  // Hoja impresa por una sola cara  // Texto a dos columnas y con orla tipográfica  // Grabado xilográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Valencia, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1444/458 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153444&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153444&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4564918",
      "autor_personas": "Laborda y Galve, Agustín -imp.  // ",
      "título": "Gozos al Niño Jesus recien nacido ",
      "editorial": "Imprenta Laborda  ",
      "lugar_publicacion": "Valencia",
      "fecha_publicacion": "entre 1830 y 1864?",
      "descripcion_fisica": "[1] h. , 31 cm. , ",
      "descripcion_notas": "Fecha de impresión deducida de los años de trabajo del impresor  // Hoja impresa por una sola cara  // Texto a dos columnas y con orla tipográfica  // Grabado xilográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Valencia, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1444/459 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153446&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153446&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4564931",
      "autor_personas": "Marti, Juan -imp.  // ",
      "título": "Gozos al Santisimo Niño Jesus de Belen, conforme se canta en la Real Capilla de Nuestra Señora de la Seo, vulgo del milagro ",
      "editorial": "Imp. y Lib. de Juan Martí  ",
      "lugar_publicacion": "Valencia",
      "fecha_publicacion": "entre 1864 y 1867?",
      "descripcion_fisica": "[1] h. , 31 cm , ",
      "descripcion_notas": "Fecha de impresión deducida de los años de trabajo del impresor en Valencia, a partir de 1867 hasta aproximadamente 1876 sólo trabaja como librero  // Texto a dos columnas y con orla tipográfica  // Hoja impresa por una sola cara  // Grabado en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Valencia, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1444/462 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153453&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153453&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4564943",
      "autor_entidades": "Viuda de Buenaventura Corominas (fl.1844-1847) -imp.  // ",
      "título": "Gozos en alabanza de Nuestra Señora de la Arcada, que se venera en su propia capilla de la calle de Zapateros de la Ciudad de Lérida ",
      "editorial": "Imp. de la C. de Corominas  ",
      "lugar_publicacion": "Lérida",
      "fecha_publicacion": "1847",
      "descripcion_fisica": "[1] h. , 31 cm , ",
      "descripcion_notas": "Texto a dos columnas y con orla tipográfica  // Hoja impresa por una sola cara  // Grabado xilográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Lérida, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/226 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153762&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153762&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4564962",
      "título": "Goigs de la sagrada imatge de Jesús Pobre, venerada en lo hospici que li fundà el venerable Pare Frare Pere Esteve una llegua de la ciutat de Denia, junt à la Montanya de Mongó ",
      "editorial": "s.n.]  ",
      "lugar_publicacion": "[S.l.",
      "fecha_publicacion": "entre 1750 y 1850?",
      "descripcion_fisica": "[1] h. , 29 cm. , ",
      "descripcion_notas": "Existen al menos dos ediciones  // Fecha de impresión deducida de la tipografía  // Texto a tres columnas y con orla tipográfica  // Hoja impresa por una sola cara  // Grabado xilográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "pais_publicacion": "xx",
      "lengua_publicacion": "cat",
      "tipo_documento": " Libro",
      "signatura": "VE/1444/466 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153459&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153459&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4564964",
      "título": "Goigs de la sagrada imatge de Jesús Pobre, venerada en lo hospici que li fundà el venerable Pare Frare Pere Esteve una llegua de la ciutat de Denia, junt à la Montanya de Mongó ",
      "editorial": "s.n.]  ",
      "lugar_publicacion": "[S.l.",
      "fecha_publicacion": "entre 1800 y 1850?",
      "descripcion_fisica": "[1] h. , 29 cm. , ",
      "descripcion_notas": "Existen al menos dos ediciones  // Fecha de impresión deducida de la tipografía  // Texto a tres columnas y con orla tipográfica  // Hoja impresa por una sola cara  // Grabado xilográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "pais_publicacion": "xx",
      "lengua_publicacion": "cat",
      "tipo_documento": " Libro",
      "signatura": "VE/1444/467 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153461&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153461&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4564973",
      "autor_personas": "Monfort, Benito , 1715-1785 -imp.  // ",
      "título": "En llaor de la gloriosa llongitut de Jesu-Christ, que es venèra en la Seu de Valencia ",
      "editorial": "por Benito Monfort  ",
      "lugar_publicacion": "En Valencia",
      "fecha_publicacion": "1765",
      "descripcion_fisica": "[1] h. , 30 cm. , ",
      "descripcion_notas": "Texto a tres columnas y con orla tipográfica  // Hoja impresa por una sola cara  // Grabado xilográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Valencia, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "cat",
      "tipo_documento": " Libro",
      "signatura": "VE/1444/468 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153462&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153462&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4564992",
      "autor_personas": "Torras, Valentín , fl.1820-1848 -imp.  // ",
      "título": "Gozos a la Gloriosa Asuncion de la Reina de los Cielos Maria Santísima ",
      "editorial": "Imprenta de V. Torras  ",
      "lugar_publicacion": "Barcelona",
      "fecha_publicacion": "1844",
      "descripcion_fisica": "[1] h. , 31 cm , ",
      "descripcion_notas": "Texto a dos columnas y con orla tipográfica  // Hoja impresa por una sola cara  // Grabado litográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Barcelona, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/227 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153763&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153763&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4564994",
      "autor_entidades": "Viuda e Hijos de Martí (Alcoy) -imp.  // ",
      "título": "Gozos a la Divina Aurora Maria Santisima ",
      "editorial": "Imprenta y L. de la Viuda é Hijos de Marti  ",
      "lugar_publicacion": "Alcoy",
      "fecha_publicacion": "1856",
      "descripcion_fisica": "[1] h. , 31 cm , ",
      "descripcion_notas": "Texto a dos columnas y con orla tipográfica  // Hoja impresa por una sola cara  // Grabado xilográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Alcoy, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/228 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153764&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153764&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4564995",
      "autor_entidades": "Librería y Tipografía Católica (Barcelona) -imp.  // ",
      "título": "Gozos á Nuestra Señora de los Afligidos venerada en su capilla de la calle de la Abadía de San Martin de Valencia ",
      "editorial": "Tipografía Católica  ",
      "lugar_publicacion": "Barcelona",
      "fecha_publicacion": "1890",
      "descripcion_fisica": "[1] h. , 32 cm. , ",
      "descripcion_notas": "Texto a tres columnas y con orla tipográfica  // Hoja impresa por una sola cara  // Grabado litográfico en cabecera  // ",
      "tema": "Virgen de los Afligidos -- Poesías --  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Barcelona, España // ",
      "cdu": "27-312.47 Virgen de los Afligidos  //  27-312.47(0:82)  //  821.134.2-14 ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/231 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153766&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153766&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4565002",
      "autor_entidades": "Librería y Tipografía Católica (Barcelona) -imp.  // ",
      "título": "Gozos á María Santísima del Águila, patrona de Alcalá de Guadaira ",
      "editorial": "Tipografía Católica  ",
      "lugar_publicacion": "Barcelona",
      "fecha_publicacion": "1892",
      "descripcion_fisica": "[1] h. , 31 cm. , ",
      "descripcion_notas": "Texto a tres columnas y con orla tipográfica  // Hoja impresa por una sola cara  // Grabado litográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Barcelona, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/232 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153767&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153767&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4565005",
      "autor_entidades": "Librería y Tipografía Católica (Barcelona)  // ",
      "título": "Gozos de Nuestra Señora de las Angustias, Patrona de la Ciudad y Reino de Granada ",
      "editorial": "Tipografía Católica  ",
      "lugar_publicacion": "Barcelona",
      "fecha_publicacion": "1891",
      "descripcion_notas": "Fecha de impresión tomada del final del texto  // Texto a tres columnas y con orla tipográfica  // Hoja impresa por una sola cara  // Grabado litográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Barcelona, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/233 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153768&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153768&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4565034",
      "autor_entidades": "Imprenta Tasso -imp.  // ",
      "título": "Gozos de Ntra. Sra. de la Almudena Patrona de la Real Villa de Madrid ",
      "editorial": "Imp. L. Tasso  ",
      "lugar_publicacion": "Barcelona",
      "fecha_publicacion": "entre 1835 y 1918?",
      "descripcion_fisica": "[1] h. , 32 cm , ",
      "descripcion_notas": "Fecha de impresión deducida de los años de trabajo del impresor  // Texto a tres columnas y con orla tipográfica  // Hoja impresa por una sola cara  // Grabado litográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Barcelona, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/236 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153771&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153771&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4565040",
      "autor_personas": "Tasso y Serra, Luis , fl. 1877-1906 -imp.  // ",
      "título": "Gozos y alabanzas en honor de María Siempre Vírgen, saludada por el arcángel llena de gracia al anunciarle el gran misterio de la encarnación del hijo de Dios en sus purísimas entrañas cual misterio se venera en la parroquial iglesia de San José ... ",
      "editorial": "Imp. de Luis Tasso  ",
      "lugar_publicacion": "Barcelona",
      "fecha_publicacion": "1877",
      "descripcion_fisica": "[1] h. , 30 cm , ",
      "descripcion_notas": "Texto a tres columnas y con orla tipográfica  // Hoja impresa por una sola cara  // Grabado litográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Barcelona, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/237 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153772&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153772&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4565046",
      "autor_entidades": "Imprenta de Torras  // ",
      "título": "Gozos de Nuestra Señora de Dos Aguas que se venera en una Capilla á un cuarto de hora de Nonaspe partido de Caspe Diócesis de Zaragoza ",
      "editorial": "Imprenta de Torras, calle de San Eusebio núm. 6  ",
      "lugar_publicacion": "San Gervasio [Barcelona]",
      "fecha_publicacion": "entre 1870 y 1900?",
      "descripcion_fisica": "[1] h. , 32 cm , ",
      "descripcion_notas": "Fecha de impresión deducida de los años de trabajo del impresor  // Texto a tres columnas y con orla tipográfica  // Hoja impresa por una sola cara  // Grabado xilográfico en cabecera  // ",
      "tema": "Virgen de Dos Aguas -- Poesías --  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Barcelona, España // ",
      "cdu": "27-312.47 Virgen de Dos Aguas  //  27-312.47(0:82)  //  821.134.2-14  // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/239 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153774&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153774&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4565102",
      "autor_entidades": "Viuda de Buenaventura Corominas (fl.1844-1847) -Imp.  // ",
      "título": "Gozos del angel jesuita San Luis Gonzaga ",
      "editorial": "imp. de la V. Corominas  ",
      "lugar_publicacion": "Lerida",
      "fecha_publicacion": "entre 1844 y 1847?",
      "descripcion_fisica": "[1] h. , 30 cm , ",
      "descripcion_notas": "Fecha de impresión deducida de los años de trabajo del taller de imprenta  // Texto a tres columnas y con orla tipográfica  // Hoja impresa por una sola cara  // Grabado xilográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Lleida, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/76 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153630&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153630&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4565129",
      "autor_personas": "Corominas, Buenaventura , m. 1841 -imp.  // ",
      "título": "Gozos en alabanza del Apostol San-tiago, Patron de las Españas que se venera en la Calle de la pescadería de la Ciudad de Lérida ",
      "editorial": "en la Imprenta de Buenaventura Corominas, Impresor y Librero  ",
      "lugar_publicacion": "Lérida",
      "fecha_publicacion": "entre 1815 y 1841?",
      "descripcion_fisica": "[1] h. , 31 cm. , ",
      "descripcion_notas": "Fecha de impresión deducida de los años de trabajo del impresor  // Hoja impresa por una sola cara  // Texto a tres columnas y con orla tipográfica  // Grabado xilográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Lleida, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/117 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153668&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153668&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4565144",
      "autor_entidades": "Imprenta de Torras -Imp.  // ",
      "título": "Gozos en honor del glorioso San Ibo, presbitero, abogado y confesor cuya imagen se venera en el altar de Ntra. Sra. de los Angeles de la parroquial iglesia de Sta. Maria del Mar de Barcelona : celebra su fiesta la Iglesia el dia 19 de Mayo ",
      "editorial": "imp. de Torras, calle de la Cruz, 66  ",
      "lugar_publicacion": "S. Gervasio [Barcelona]",
      "fecha_publicacion": "1892",
      "descripcion_fisica": "[1] h. , 32 cm. , ",
      "descripcion_notas": "Texto a tres columnas y con orla tipográfica  // Hoja impresa por una sola cara  // Grabado xilográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Barcelona, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/137 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153686&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153686&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4565464",
      "autor_entidades": "Imprenta de Ángel Camí y José Arnavat -Imp.  // ",
      "título": "Gozos en alabanza del angelico joven S. Luis Gonzaga, de la Compañía de Jesus, patron de los jóvenes ",
      "editorial": "reimpreso por Camí y Arnavat  ",
      "lugar_publicacion": "Reus",
      "fecha_publicacion": "entre 1845 y 1855?",
      "descripcion_fisica": "[1] h. , 32 cm , ",
      "descripcion_notas": "Fecha de impresión deducida de los años de trabajo de la imprenta  // Texto a tres columnas y con orla tipográfica  // Hoja impresa por una sola cara  // Grabado xilográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Reus, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/77 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153631&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153631&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4565493",
      "autor_entidades": "Imprenta de El Porvenir de Buenaventura Bassas (Barcelona) -Imp.  // ",
      "título": "Gozos en honor del glorioso obispo y martir San Severo, abogado contra dolor de cabeza que se cantan en su insigne iglesia de Barcelona agregada á la de S. Juan de Letran de Roma ",
      "editorial": "imp. de la viuda Bassas, á cargo de J. Medina, Tallers, 51  ",
      "lugar_publicacion": "Barcelona",
      "fecha_publicacion": "1866",
      "descripcion_fisica": "[1] h. , 31 cm , ",
      "descripcion_notas": "Texto a tres columnas y con orla tipográfica  // Hoja impresa por una sola cara  // Grabado xilográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Barcelona, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/80 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153634&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153634&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4565525",
      "autor_personas": "Guasp, Felipe -imp.  // ",
      "título": "San Serapio mártir, caballero laico, religioso Mercedario, abogado de todo género de dolores, descoyunturas, quebraduras y llagas ... ",
      "editorial": "imprenta de F. Guasp  ",
      "lugar_publicacion": "[Palma de Mallorca]",
      "fecha_publicacion": "entre 1812 y 1862?",
      "descripcion_fisica": "[1] h.; 31 cm. , ",
      "descripcion_notas": "Lugar y fechas de impresión deducidos de los datos de actividad de la imprenta  // Texto a tres columnas y con orla tipográfica  // Hoja impresa por una sola cara  // Grabado xilográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Palma de Mallorca, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/82 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153636&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153636&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4565593",
      "autor_entidades": "Librería y Tipografía Católica (Barcelona) -Imp.  // ",
      "título": "Gozos en honor del glorioso San Millan de la Cogulla [sic], presbítero y confesor cuyo sagrado cuerpo se venera en un suntuoso monasterio ... ",
      "informacion_asociada_titulo": "(compuestos por G. S. P.) ",
      "editorial": "Tipografía Católica, Pino, 5  ",
      "lugar_publicacion": "Barcelona",
      "fecha_publicacion": "entre 1870 y 1900?",
      "descripcion_fisica": "[1] h. , 32 cm , ",
      "descripcion_notas": "Por tipografía, impreso en el siglo XIX: la Tip. Católica comienza a imprimir en 1870  // Texto a tres columnas y con orla tipográfica  // Hoja impresa por una sola cara  // Grabado litográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Barcelona, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/91 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153645&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153645&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4565653",
      "autor_personas": "Biarnès, Françesc -imp.  // ",
      "título": "Gozos de San Mauro Abad ",
      "editorial": "imp. de F. Biarnes, Cambios, 3  ",
      "lugar_publicacion": "Tortosa",
      "fecha_publicacion": "entre 1895 y 1910?",
      "descripcion_fisica": "[1] h. , 31 cm. , ",
      "descripcion_notas": "Fechas de impresión deducidas de los años de actividad del impresor  // Texto a dos columnas y con orla tipográfica  // Hoja impresa por una sola cara  // Grabado xilográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Tortosa, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/93 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153647&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153647&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4565810",
      "autor_entidades": "Imprenta Peninsular (Barcelona) -Imp.  // ",
      "título": "Gozos del arcangel S. Miguel ",
      "editorial": "imp. Peninsular, Asalto-69  ",
      "lugar_publicacion": "[Barcelona]",
      "fecha_publicacion": "entre 1875 y 1884?",
      "descripcion_fisica": "[1] h. , 31 cm , ",
      "descripcion_notas": "Lugar y fechas de impresión deducidas de los años de actividad de la imprenta  // Texto a dos columnas y con orla tipográfica  // Hoja impresa por una sola cara  // Grabado litográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Barcelona, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/94 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153648&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153648&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4565854",
      "título": "Gozos de San Ildefonso, arzobispo y confesor cuya fiesta se celebra el 28 de Enero ",
      "editorial": "s.n.]  ",
      "lugar_publicacion": "[S.l.",
      "fecha_publicacion": "1886",
      "descripcion_fisica": "[1] h. , 30 cm , ",
      "descripcion_notas": "Texto a tres columnas y con orla tipográfica  // Hoja impresa por una sola cara  // Grabado en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/138 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153687&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153687&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4565871",
      "autor_personas": "Tasso y Serra, Luis , fl. 1877-1906 -imp.  // ",
      "título": "Gozos en honor de San Isidoro, Obispo, Confesor y Doctor de la Iglesia su fiesta en 4 de abril ",
      "editorial": "imp. Tasso, Arco del Teatro, 21 y 23  ",
      "lugar_publicacion": "[Barcelona]",
      "fecha_publicacion": "1885",
      "descripcion_fisica": "[1] h. , 32 cm , ",
      "descripcion_notas": "Lugar de impresión deducido de los datos de actividad de la imprenta  ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Barcelona, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/139 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153688&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153688&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4565877",
      "autor_entidades": "Imprenta de Torras -imp.  // ",
      "título": "Gozos de la Santisima Vírgen Nuestra Señora de Aranzazu, Patrona de Guipuscoa venerada en su Templo, en la jurisicion de Oñate, Obispado de Calahorra ",
      "editorial": "Imp. de Torras, calle de S. Eusebio núm. 6  ",
      "lugar_publicacion": "S. Gervasio [Barcelona]",
      "fecha_publicacion": "1885",
      "descripcion_fisica": "[1] h. , 31 cm , ",
      "descripcion_notas": "Texto a tres columnas y con orla tipográfica  // Hoja impresa por una sola cara  // Grabado xilográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Barcelona, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/241 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153776&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153776&first=1&last=2 ** "
    },
    {
      "id_BNE": "a4565890",
      "autor_entidades": "Librería de los Sucesores de Font (Barcelona) -ed.  // ",
      "título": "Gozos á la Reina de los Santos Maria Santísima, en su gloriosa asuncion a los cielos que se venera en la Parroquial Iglesia de los Stos. Justo y Pastor de la presente Ciudad ",
      "editorial": "Libreria de los sucesores de Font  ",
      "lugar_publicacion": "Barcelona",
      "fecha_publicacion": "entre 1860 y 1900?",
      "descripcion_fisica": "[1] h. , 31 cm , ",
      "descripcion_notas": "Fecha de impresión deducida de los años de trabajo del impresor  // Texto a dos columnas y con orla tipográfica  // Hoja impresa por una sola cara  // Grabado litográfico en cabecera  // ",
      "genero_forma": "Gozos --  // ",
      "lugar_relacionado": "Barcelona, España // ",
      "pais_publicacion": "sp",
      "lengua_publicacion": "spa",
      "tipo_documento": " Libro",
      "signatura": "VE/1445/242 // ",
      "version_digital": "http://bdh-rd.bne.es/viewer.vm?id=0000153777&page=1 ** ",
      "texto_OCR": "http://bdh-rd.bne.es/text.vm?id=0000153777&first=1&last=2 ** "
    }
]`;

var objBDH = JSON.parse(cadJsonBDH);

